export const remoteCompanies = [
  { name: "Accenture", url: "https://www.accenture.com/us-en/careers" },
  { name: "Adobe", url: "https://www.adobe.com/careers.html" },
  { name: "Affirm", url: "https://www.affirm.com/careers" },
  { name: "Airbnb", url: "https://careers.airbnb.com/" },
  { name: "Alation", url: "https://www.alation.com/careers/" },
  { name: "Algolia", url: "https://www.algolia.com/careers/" },
  { name: "Alteryx", url: "https://www.alteryx.com/careers" },
  { name: "Amazon (AWS)", url: "https://www.amazon.jobs/en/teams/amazon-web-services" },
  { name: "AMD", url: "https://careers.amd.com/" },
  { name: "American Express", url: "https://careers.americanexpress.com/" },
  { name: "Andela", url: "https://andela.com/careers/" },
  { name: "Ancestry", url: "https://www.ancestry.com/careers/" },
  { name: "Anthropic", url: "https://www.anthropic.com/careers" },
  { name: "Appian", url: "https://www.appian.com/company/careers/" },
  { name: "Apple", url: "https://www.apple.com/careers/" },
  { name: "AppFolio", url: "https://www.appfolioinc.com/company/careers" },
  { name: "Asana", url: "https://asana.com/jobs" },
  { name: "Atlassian", url: "https://www.atlassian.com/company/careers" },
  { name: "Automattic", url: "https://automattic.com/work-with-us/" },
  { name: "AvaLabs", url: "https://www.avax.network/careers" },
  { name: "Axiom", url: "https://www.axiom.co/careers" },
  { name: "Bank of America", url: "https://careers.bankofamerica.com/" },
  { name: "BlackRock", url: "https://careers.blackrock.com/" },
  { name: "Blend", url: "https://blend.com/company/careers/" },
  { name: "Block (Square)", url: "https://block.xyz/careers" },
  { name: "Bloomberg", url: "https://www.bloomberg.com/careers/technology" },
  { name: "Bolt", url: "https://www.bolt.com/careers" },
  { name: "Box", url: "https://careers.box.com/" },
  { name: "Braze", url: "https://www.braze.com/company/careers" },
  { name: "Broadcom (VMware)", url: "https://careers.broadcom.com/" },
  { name: "Canva", url: "https://www.canva.com/careers/" },
  { name: "Capgemini", url: "https://www.capgemini.com/careers/" },
  { name: "Capital One", url: "https://www.capitalonecareers.com/" },
  { name: "Carta", url: "https://carta.com/careers/" },
  { name: "Celonis", url: "https://www.celonis.com/careers/" },
  { name: "Ceridian (Dayforce)", url: "https://www.dayforce.com/careers" },
  { name: "Chargebee", url: "https://www.chargebee.com/careers/" },
  { name: "Cisco", url: "https://jobs.cisco.com/" },
  { name: "Citigroup", url: "https://jobs.citi.com/" },
  { name: "Cloudflare", url: "https://www.cloudflare.com/careers/" },
  { name: "Cognizant", url: "https://www.cognizant.com/us/en/careers" },
  { name: "Coinbase", url: "https://www.coinbase.com/careers" },
  { name: "Comcast", url: "https://jobs.comcast.com/" },
  { name: "Confluent", url: "https://www.confluent.io/careers/" },
  { name: "CrowdStrike", url: "https://www.crowdstrike.com/careers/" },
  { name: "Databricks", url: "https://www.databricks.com/company/careers" },
  { name: "Datadog", url: "https://www.datadoghq.com/careers/" },
  { name: "Dealertrack (Cox)", url: "https://jobs.coxenterprises.com/" },
  { name: "Deloitte", url: "https://www2.deloitte.com/global/en/careers" },
  { name: "DoorDash", url: "https://careers.doordash.com/" },
  { name: "Dropbox (Virtual First)", url: "https://www.dropbox.com/jobs" },
  { name: "eBay", url: "https://jobs.ebayinc.com/" },
  { name: "Elastic", url: "https://www.elastic.co/about/careers" },
  { name: "Electronic Arts", url: "https://www.ea.com/careers" },
  { name: "EPAM Systems", url: "https://www.epam.com/careers" },
  { name: "Etsy", url: "https://careers.etsy.com/global/en" },
  { name: "Evernote", url: "https://evernote.com/careers" },
  { name: "Expedia Group", url: "https://lifeatexpediagroup.com/jobs" },
  { name: "Fidelity Investments", url: "https://jobs.fidelity.com/" },
  { name: "Figma", url: "https://www.figma.com/careers/" },
  { name: "Flexport", url: "https://flexport.com/careers" },
  { name: "GitHub", url: "https://github.com/about/careers" },
  { name: "GitLab", url: "https://about.gitlab.com/jobs/" },
  { name: "Gusto", url: "https://gusto.com/about/careers" },
  { name: "HashiCorp", url: "https://www.hashicorp.com/careers" },
  { name: "HCLTech", url: "https://www.hcltech.com/careers" },
  { name: "Help Scout", url: "https://www.helpscout.com/company/careers/" },
  { name: "Honeywell", url: "https://careers.honeywell.com/" },
  { name: "Hopin", url: "https://hopin.com/careers" },
  { name: "HP", url: "https://jobs.hp.com/" },
  { name: "HubSpot", url: "https://www.hubspot.com/careers" },
  { name: "IBM", url: "https://www.ibm.com/careers/us-en/" },
  { name: "ICF", url: "https://www.icf.com/careers" },
  { name: "Indeed", url: "https://www.indeed.jobs/" },
  { name: "Informatica", url: "https://www.informatica.com/about-us/careers.html" },
  { name: "Infosys", url: "https://www.infosys.com/careers" },
  { name: "Intel", url: "https://jobs.intel.com/" },
  { name: "Intuit", url: "https://www.intuit.com/careers/" },
  { name: "Invitae", url: "https://careers.invitae.com/" },
  { name: "JP Morgan Chase", url: "https://careers.jpmorgan.com/" },
  { name: "Klaviyo", url: "https://www.klaviyo.com/careers" },
  { name: "KPMG", url: "https://www.kpmgcareers.us/" },
  { name: "Lattice", url: "https://lattice.com/careers" },
  { name: "LinkedIn", url: "https://careers.linkedin.com/" },
  { name: "Lyft", url: "https://www.lyft.com/careers" },
  { name: "Mastercard", url: "https://careers.mastercard.com/" },
  { name: "Meta", url: "https://www.metacareers.com/" },
  { name: "Microsoft", url: "https://careers.microsoft.com/" },
  { name: "MongoDB", url: "https://www.mongodb.com/careers" },
  { name: "Netflix", url: "https://jobs.netflix.com/" },
  { name: "New Relic", url: "https://newrelic.com/about/careers" },
  { name: "Nvidia", url: "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite" },
  { name: "Okta", url: "https://www.okta.com/company/careers/" },
  { name: "Oracle", url: "https://careers.oracle.com/" },
  { name: "Palantir", url: "https://www.palantir.com/careers/" },
  { name: "PayPal", url: "https://www.paypal.com/us/webapps/mpp/jobs" },
  { name: "Pinterest", url: "https://www.pinterestcareers.com/" },
  { name: "Plaid", url: "https://plaid.com/careers/" },
  { name: "Salesforce", url: "https://www.salesforce.com/company/careers/" },
  { name: "ServiceNow", url: "https://www.servicenow.com/careers.html" },
  { name: "Shopify", url: "https://www.shopify.com/careers" },
  { name: "Slack", url: "https://slack.com/careers" },
  { name: "Snowflake", url: "https://www.snowflake.com/careers/" },
  { name: "Spotify", url: "https://www.lifeatspotify.com/" },
  { name: "Stripe", url: "https://stripe.com/jobs" },
  { name: "Uber", url: "https://www.uber.com/us/en/careers/" },
  { name: "Workday", url: "https://www.workday.com/en-us/company/careers.html" },
  { name: "Zoom", url: "https://careers.zoom.us/" },
];
