// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
const SUPABASE_URL = "https://llcqdqwkvdxxwwmpyglr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxsY3FkcXdrdmR4eHd3bXB5Z2xyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1OTg0OTQsImV4cCI6MjA3ODE3NDQ5NH0.ZIrlDyYs18T-Xx0tFF5RmN3Ccj8kBDuvP52FEHfyxoc";


// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});